### ISSUE TITLE
Trello User Story List

### ISSUE THREAD

**Issue by nachiketkb** [vipragupta/Software-Project#1]
In Trello message board, do we need a single todo list for all user stories or can we create separate todo lists for every user?

Like this:

![image](https://cloud.githubusercontent.com/assets/4459920/19019080/396dd9d8-8836-11e6-8cf8-fb8e5a9bf287.png)

**Comment by kenbod** [comment]
You can definitely have separate lists for each of the different user types. You can also have two lists for each user type, one which has user stories and one which has developer tasks. Work to find a structure that helps you keep track of what needs to be done.
